[package]
name = "blockchain1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.14.12"

[lib]
name = "blockchain1"
crate-type = ["cdylib", "lib"]